### PR TITLE
wrapper: try to notice the last error

### PR DESCRIPTION
**Pull request by zellyn**
After executing all commands, make one last check on the error
channel, to see whether the last command errored.

### CODE REVIEW

**Comment by zellyn** [comment]
@bwester @baweaver @mpuncel

**Review by bwester — APPROVED** [review]

**Comment by bwester** [comment]
This change looks good to me.

Incidental to your change, I think there can also be a very low-probability deadlock in that function, where one worker goroutine is attempting to push an error value into a full channel while the manager waits on the `WaitGroup` for the goroutine to exit.

**Comment by baweaver** [comment]
LGTM

**Comment by zellyn** [comment]
@bwester you're completely right. I gave the error channel `parallelism` capacity, but of course there could be way more errors. Will look into it tomorrow.

**Pull request merged**
